source 'http://rubygems.org'

gem 'sinatra', :require => false #, require: 'sinatra/base'
gem 'rake'
gem 'thin'
gem 'rerun'
gem 'twitter'
gem 'redis'
gem 'sidekiq'
gem 'sinatra-contrib'
gem 'sidetiq'
